# Generated by Django 2.2.28 on 2022-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_year', models.DateField()),
                ('instituate', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expriences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joning_date', models.DateField()),
                ('leav_date', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_mail', models.EmailField(max_length=254)),
                ('sender_message', models.TextField()),
                ('send_date', models.DateField(auto_now=True, null=True)),
                ('send_time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_caption', models.CharField(max_length=20)),
                ('skill_des', models.CharField(max_length=100)),
            ],
        ),
    ]
